ros2 run pointcloud_to_laserscan pointcloud_to_laserscan_node --ros-args     
-r cloud_in:=/livox/lidar     
-r scan:=/scan     
-p target_frame:=livox_frame     
-p queue_size:=40     
-p min_height:=-5.0     
-p max_height:=5.0   
 -p angle_min:=-3.14159     
 -p angle_max:=3.14159     
 -p angle_increment:=0.0087     
 -p scan_time:=0.1    
-p range_min:=0.2     
-p range_max:=25.0     
-p use_inf:=true
